# Pandas

Pandas provides **Series** and **DataFrame** data structures to Python in addition to data input/output functions, basic data analysis tools, utilities and plotting capabilities. It builds on top of NumPy ndarray. Pandas is squished form of **Panel Data Structure**. Pandas is primarily used for data munging and preparation but also provides some data analysis tools. Pandas does not implement any significant modeling functionality other than simple linear and panel regression. For these, you can use statsmodels and scikit-learn which build on top of the DataFrame data structure.

In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [2]:
data = np.random.randn(6, 4)
df = pd.DataFrame(data, columns=list('ABCD'))
print(df)

          A         B         C         D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310
3 -0.049324  0.079400  0.613973  0.728616
4  0.093288  0.776683  0.331441 -0.500431
5 -0.061561  0.412056 -0.355617  0.244264


## Properties of DataFrame

In [3]:
print('Shape:', df.shape)
print('Data Types:', df.dtypes)
print('Column Labels:', df.columns)
print(df.index)

Shape: (6, 4)
Data Types: A    float64
B    float64
C    float64
D    float64
dtype: object
Column Labels: Index(['A', 'B', 'C', 'D'], dtype='object')
RangeIndex(start=0, stop=6, step=1)


In [4]:
print(df.head())

          A         B         C         D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310
3 -0.049324  0.079400  0.613973  0.728616
4  0.093288  0.776683  0.331441 -0.500431


In [5]:
print(df.tail())

          A         B         C         D
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310
3 -0.049324  0.079400  0.613973  0.728616
4  0.093288  0.776683  0.331441 -0.500431
5 -0.061561  0.412056 -0.355617  0.244264


In [6]:
print(df.head(3))

          A         B         C         D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310


## Indexing and Slicing DataFrame

In [7]:
print(type(df['A'])) # Each column of a DataFrame is a Series

<class 'pandas.core.series.Series'>


In [8]:
print(df['A']) # Copy elements of column A, retaining the row indices

0    0.934879
1    1.811006
2    0.242163
3   -0.049324
4    0.093288
5   -0.061561
Name: A, dtype: float64


In [9]:
print(type(df.loc[1, :])) # Each row of a DataFrame is a Series
print(df.loc[1, :]) # Copy row with index 1

<class 'pandas.core.series.Series'>
A    1.811006
B    0.182170
C    0.015382
D   -2.310417
Name: 1, dtype: float64


In [10]:
print(df.A) # Column is accessed using name of column and the dot notation (provided column name has no spaces)

0    0.934879
1    1.811006
2    0.242163
3   -0.049324
4    0.093288
5   -0.061561
Name: A, dtype: float64


In [11]:
print(df.A[1]) # Column A, row index 1

1.8110056126414085


In [12]:
print(df.loc[0:2, :]) # 0:2 includes the stop index 2, unlike slicing in NumPy

          A         B         C         D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310


In [13]:
df.columns = ['Column A', 'Column B', 'Column C', 'Column D'] # Column names can be changed, and can contain spaces
print(df.head(3))

   Column A  Column B  Column C  Column D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310


In [14]:
print(df['Column C'][0:3]) # Slicing follows normal Python rules in this case

0    0.091423
1    0.015382
2    1.799558
Name: Column C, dtype: float64


In [15]:
print(df[['Column A', 'Column C']][0:3]) # You can choose the columns and rows to copy

   Column A  Column C
0  0.934879  0.091423
1  1.811006  0.015382
2  0.242163  1.799558


In [16]:
print(df[['Column D', 'Column A']][5:2:-1]) # Order of rows and columns can be chosen by user

   Column D  Column A
5  0.244264 -0.061561
4 -0.500431  0.093288
3  0.728616 -0.049324


In [17]:
print(df['Column B'] * 2)

0   -0.268425
1    0.364340
2    3.675365
3    0.158800
4    1.553367
5    0.824112
Name: Column B, dtype: float64


In [18]:
print(type(df.to_numpy()))

<class 'numpy.ndarray'>


In [19]:
print(df.to_numpy())

[[ 0.93487854 -0.13421273  0.09142278 -0.78232389]
 [ 1.81100561  0.18217004  0.0153821  -2.31041697]
 [ 0.24216259  1.83768236  1.79955793  0.47831045]
 [-0.04932415  0.07939982  0.61397325  0.72861638]
 [ 0.09328816  0.77668344  0.33144123 -0.50043096]
 [-0.06156113  0.41205597 -0.35561666  0.24426424]]


In [20]:
print(df.index.array)

<PandasArray>
[0, 1, 2, 3, 4, 5]
Length: 6, dtype: int64


In [21]:
df.columns.array

<PandasArray>
['Column A', 'Column B', 'Column C', 'Column D']
Length: 4, dtype: object

## Boolean Operations

In [22]:
df.columns = list('ABCD')
print(df.A > 0)

0     True
1     True
2     True
3    False
4     True
5    False
Name: A, dtype: bool


In [23]:
df[df.A > 0]

A         B         C         D
0  0.934879 -0.134213  0.091423 -0.782324
1  1.811006  0.182170  0.015382 -2.310417
2  0.242163  1.837682  1.799558  0.478310
4  0.093288  0.776683  0.331441 -0.500431

In [24]:
indx = df[df.B > 0].index
print(indx)

Int64Index([1, 2, 3, 4, 5], dtype='int64')


In [25]:
df.loc[indx, ['B', 'D']]

B         D
1  0.182170 -2.310417
2  1.837682  0.478310
3  0.079400  0.728616
4  0.776683 -0.500431
5  0.412056  0.244264

In [26]:
df['E'] = 'Non positive' # Creates a new column E, and populates the column with Non positive
df.loc[indx, 'E'] = 'Positive' # Overwrites column E of rows of with index in indx
print(df)

          A         B         C         D             E
0  0.934879 -0.134213  0.091423 -0.782324  Non positive
1  1.811006  0.182170  0.015382 -2.310417      Positive
2  0.242163  1.837682  1.799558  0.478310      Positive
3 -0.049324  0.079400  0.613973  0.728616      Positive
4  0.093288  0.776683  0.331441 -0.500431      Positive
5 -0.061561  0.412056 -0.355617  0.244264      Positive


## Reading and Writing MS Excel and CSV Files

Most data is available in one of several common formats, such as, CSV, MS Excel, HDF5, SQL. Pandas provides functions to read and write all such formats.

In [27]:
fn = 'PCA CDB-2901-F-Census.xlsx'
df_bgm = pd.read_excel(pd.ExcelFile(fn))
print(f"{fn}: {len(df_bgm)} records")
print(f"{len(df_bgm.columns)} columns")
print(df_bgm.columns.array)

PCA CDB-2901-F-Census.xlsx: 1323 records
95 columns
<PandasArray>
[         'State',       'District',        'DT Name',       'CD Block',
   'Town/Village',           'Ward',             'EB',          'Level',
           'Name',            'TRU',          'No_HH',          'TOT_P',
          'TOT_M',          'TOT_F',           'P_06',           'M_06',
           'F_06',           'P_SC',           'M_SC',           'F_SC',
           'P_ST',           'M_ST',           'F_ST',          'P_LIT',
          'M_LIT',          'F_LIT',          'P_ILL',          'M_ILL',
          'F_ILL',     'TOT_WORK_P',     'TOT_WORK_M',     'TOT_WORK_F',
     'MAINWORK_P',     'MAINWORK_M',     'MAINWORK_F',      'MAIN_CL_P',
      'MAIN_CL_M',      'MAIN_CL_F',      'MAIN_AL_P',      'MAIN_AL_M',
      'MAIN_AL_F',      'MAIN_HH_P',      'MAIN_HH_M',      'MAIN_HH_F',
      'MAIN_OT_P',      'MAIN_OT_M',      'MAIN_OT_F',     'MARGWORK_P',
     'MARGWORK_M',     'MARGWORK_F',      'MARG_CL_P',    

In [28]:
p_tot = df_bgm['TOT_P'].sum()
p_male = df_bgm['TOT_M'].sum()
p_female = df_bgm['TOT_F'].sum()
p_lit = df_bgm['P_LIT'].sum()
p_litm = df_bgm['M_LIT'].sum()
p_litf = df_bgm['F_LIT'].sum()
p_scm = df_bgm['M_SC'].sum()
p_scf = df_bgm['F_SC'].sum()
print(p_tot, p_lit, p_lit * 100 / p_tot)
print(p_lit, p_litm, p_litf, p_litm+p_litf-p_lit)

11168997 6751338 60.447128779782105
6751338 3894327 2857011 0


In [29]:
df_blr = pd.read_excel(pd.ExcelFile('PCA CDB-2918-F-Census.xlsx'))
print(f"{fn}: {len(df_blr)} records")
print(f"{len(df_blr.columns)} columns")
print(df_blr.columns.array)

PCA CDB-2901-F-Census.xlsx: 625 records
95 columns
<PandasArray>
[         'State',       'District',        'DT Name',       'CD Block',
   'Town/Village',           'Ward',             'EB',          'Level',
           'Name',            'TRU',          'No_HH',          'TOT_P',
          'TOT_M',          'TOT_F',           'P_06',           'M_06',
           'F_06',           'P_SC',           'M_SC',           'F_SC',
           'P_ST',           'M_ST',           'F_ST',          'P_LIT',
          'M_LIT',          'F_LIT',          'P_ILL',          'M_ILL',
          'F_ILL',     'TOT_WORK_P',     'TOT_WORK_M',     'TOT_WORK_F',
     'MAINWORK_P',     'MAINWORK_M',     'MAINWORK_F',      'MAIN_CL_P',
      'MAIN_CL_M',      'MAIN_CL_F',      'MAIN_AL_P',      'MAIN_AL_M',
      'MAIN_AL_F',      'MAIN_HH_P',      'MAIN_HH_M',      'MAIN_HH_F',
      'MAIN_OT_P',      'MAIN_OT_M',      'MAIN_OT_F',     'MARGWORK_P',
     'MARGWORK_M',     'MARGWORK_F',      'MARG_CL_P',     

In [32]:
movies = pd.read_csv('movies.csv')
print(len(movies))
movies.info()

9742
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
movieId    9742 non-null int64
title      9742 non-null object
genres     9742 non-null object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB


In [34]:
ratings = pd.read_csv('ratings.csv')
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
userId       100836 non-null int64
movieId      100836 non-null int64
rating       100836 non-null float64
timestamp    100836 non-null int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [35]:
links = pd.read_csv('links.csv')
links.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
movieId    9742 non-null int64
imdbId     9742 non-null int64
tmdbId     9734 non-null float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB


In [37]:
tags = pd.read_csv('tags.csv')
tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
userId       3683 non-null int64
movieId      3683 non-null int64
tag          3683 non-null object
timestamp    3683 non-null int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB


In [38]:
m = pd.merge(movies, links, on='movieId', how='inner')
m.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  imdbId   tmdbId  
0  Adventure|Animation|Children|Comedy|Fantasy  114709    862.0  
1                   Adventure|Children|Fantasy  113497   8844.0  
2                               Comedy|Romance  113228  15602.0  
3                         Comedy|Drama|Romance  114885  31357.0  
4                                       Comedy  113041  11862.0

In [39]:
tags[tags['movieId']==1]['tag']

629     pixar
981     pixar
2886      fun
Name: tag, dtype: object

In [40]:
mean_ratings = ratings.groupby('movieId', as_index=False)['rating'].mean()

In [83]:
mean_ratings

movieId    rating
0           1  3.920930
1           2  3.431818
2           3  3.259615
3           4  2.357143
4           5  3.071429
...       ...       ...
9719   193581  4.000000
9720   193583  3.500000
9721   193585  3.500000
9722   193587  3.500000
9723   193609  4.000000

[9724 rows x 2 columns]

In [41]:
m = m.merge(mean_ratings, on='movieId', how='inner').sort_values(['rating'], ascending=False)

In [82]:
m

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9719   193581  Black Butler: Book of the Atlantic (2017)   
9720   193583               No Game No Life: Zero (2017)   
9721   193585                               Flint (2017)   
9722   193587        Bungo Stray Dogs: Dead Apple (2018)   
9723   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres   imdbId    tmdbId    rating  
0     Adventure|Animation|Children|Comedy|Fantasy   114709     862.0  3.920930  
1                      Adventure|Children|Fantasy   113497    8844.0  3.431818  
2                                  Comedy|Romance   113228   15602.0  3.259615  
3                            Comedy|Drama|Romance   114885   31357.0  2.357143  
4                                          Comedy   113041   11862.0  3.071429  
...                                           ...      ...       ...       ...  
9719              Action|Animation|Comedy|Fantasy  5476944  432131.0  4.000000  
9720                     Animation|Comedy|Fantasy  5914996  445030.0  3.500000  
9721                                        Drama  6397426  479308.0  3.500000  
9722                             Action|Animation  8391976  483455.0  3.500000  
9723                                       Comedy   101726   37891.0  4.000000  

[9724 rows x 6 columns]

## apply()

Pandas has several commonlyy required functions such as `count()`, `sum()`, `mean` that can be applied to values in a column to generate a new value. However, it is possible to write a Python function and apply it to the value in a column taking one row at a time. The Python function can involve any complex logic in order to generate the value. It is also possible to take values from more than one column as well as other data as inputs to the Python function if need be.

In [87]:
df_marks = pd.DataFrame({'usn': [1, 2, 3, 4, 5], 'marks': [25, 40, 51, 64, 85]})
df_marks

usn  marks
0    1     25
1    2     40
2    3     51
3    4     64
4    5     85

In [89]:
def calc_grade(marks):
    if marks < 40:
        return 'F'
    elif marks < 51:
        return 'E'
    elif marks < 61:
        return 'D'
    elif marks < 71:
        return 'C'
    elif marks < 81:
        return 'B'
    elif marks < 91:
        return 'A'
    elif marks < 101:
        return 'S'
    else:
        return None

df_marks['marks'].apply(calc_grade)

0    F
1    E
2    D
3    C
4    A
Name: marks, dtype: object

## pandasql

pandasql is a Python package that allows 

In [90]:
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

res = pysqldf('SELECT * FROM movies')
print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [91]:
q = '''SELECT movies.movieId, movies.title, COUNT(ratings.movieId), AVG(ratings.rating) FROM movies LEFT JOIN ratings ON movies.movieId=ratings.movieId GROUP BY movies.movieId ORDER BY AVG(ratings.rating) DESC'''
#q = 'SELECT movies.movieId, movies.title, links.imdbId FROM movies LEFT JOIN links ON movies.movieId=links.movieId'
pysqldf(q)

movieId                                         title  \
0      187717              Won't You Be My Neighbor? (2018)   
1      184245                       De platte jungle (1978)   
2      179135                         Blue Planet II (2017)   
3      179133                         Loving Vincent (2017)   
4      176601                                  Black Mirror   
...       ...                                           ...   
9737     4194                I Know Where I'm Going! (1945)   
9738     3456  Color of Paradise, The (Rang-e khoda) (1999)   
9739     3338                        For All Mankind (1989)   
9740     2939                                Niagara (1953)   
9741     1076                         Innocents, The (1961)   

      COUNT(ratings.movieId)  AVG(ratings.rating)  
0                          1                  5.0  
1                          1                  5.0  
2                          1                  5.0  
3                          1                  5.0  
4                          1                  5.0  
...                      ...                  ...  
9737                       0                  NaN  
9738                       0                  NaN  
9739                       0                  NaN  
9740                       0                  NaN  
9741                       0                  NaN  

[9742 rows x 4 columns]

In [92]:
g = ratings.groupby('movieId', as_index=False)['rating'].mean().sort_values('rating', ascending=False).merge(movies, on='movieId')
g

movieId  rating                                  title  \
0       88448     5.0  Paper Birds (Pájaros de papel) (2010)   
1      100556     5.0             Act of Killing, The (2012)   
2      143031     5.0                        Jump In! (2007)   
3      143511     5.0                           Human (2015)   
4      143559     5.0                    L.A. Slasher (2015)   
...       ...     ...                                    ...   
9719   157172     0.5  Wizards of the Lost Kingdom II (1989)   
9720    85334     0.5           Hard Ticket to Hawaii (1987)   
9721    53453     0.5   Starcrash (a.k.a. Star Crash) (1978)   
9722     8494     0.5             Cincinnati Kid, The (1965)   
9723    71810     0.5                     Legionnaire (1998)   

                               genres  
0                        Comedy|Drama  
1                         Documentary  
2                Comedy|Drama|Romance  
3                         Documentary  
4                Comedy|Crime|Fantasy  
...                               ...  
9719                   Action|Fantasy  
9720                    Action|Comedy  
9721  Action|Adventure|Fantasy|Sci-Fi  
9722                            Drama  
9723       Action|Adventure|Drama|War  

[9724 rows x 4 columns]

# References
* [Official Pandas tutorials](https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html)
* [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#min)
* [Intro to pandas data structures by Greg Reda](http://www.gregreda.com/2013/10/26/intro-to-pandas-data-structures/)
* [pandasql](https://github.com/yhat/pandasql/)